### ISSUE TITLE
No horizontal scroll bar on FLA presets when they're too big

### ISSUE THREAD

**Issue by ShadabMir** [Avis-Drone-Labs/FGCS#390]
There should be a scroll bar here, or you can try make the text overflow onto multiple lines.

Edit: After some thought, multiple lines would be nicer

![Image](https://github.com/user-attachments/assets/2e8fb942-dfd2-4778-b39a-cce95adf8cbb)

**Comment by david-gasinski** [comment]
Going to use this version
![Image](https://github.com/user-attachments/assets/5b3f40bb-962f-4090-8a6e-7ae67d642353)
